### ISSUE TITLE
Use systemu

### ISSUE THREAD

**Issue by nwmcsween** [cldwalker/bahia#1]
Use systemu instead of open3

**Comment by cldwalker** [comment]
While systemu is used by the community, it's lack of testing will prevent me from using it as a dependency. Open3 on the other hand has [some tests](https://github.com/ruby/ruby/blob/trunk/test/test_open3.rb). Also, I don't know what systemu offers over open3, windows support (which I don't care about)?

**Comment by cldwalker** [comment]
He actually added tests which is cool but jruby doesn't work. I submitted https://github.com/ahoward/systemu/pull/17 so we'll see. In the meantime I'm using another of his gems to get cross-ruby support. Closing
