### ISSUE TITLE
Private fence is missing.

### ISSUE THREAD

**Issue by mnoble** [cldwalker/bahia#2]
I can't tell where the private methods are.

**Comment by cldwalker** [comment]
Ha! If only vim had emoji support I _would_ build these fences:

:poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop:

But until then, NEVERRRR
